config/routes.rb
Joal::Application.routes.draw do

  resources :problems do
    member do
      get :mark
    end
  end 
  
  resources :problems do
    resources :solutions
  end
 
  resources :problems do
     member do 
        get :top_users
     end
  end

  
  get "home/index"
  match '' => 'home#index', :as => :home

  resources :users
  resources :users, :user_sessions
  resources :users do
	resources :solutions
  end
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

   root :to => 'home#index'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :code, :description, :input, :name, :output, :test_case_in, :test_case_out
  validates :name,          :presence => true
  validates :description,   :presence => true
  validates :code,          :presence => true,
  				  :length   => {:is =>5},
                                  :uniqueness => true
  validates :description,   :presence => true
  validates :input,         :presence => true
  validates :output,        :presence => true
  validates :test_case_in,  :presence => true
  validates :test_case_out, :presence => true
  has_many:solutions
  has_many:users, :through => :solutions
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  skip_before_filter :authorization, :only => [:show, :index, :mark, :top_users, :problem_solved]
  skip_before_filter :require_login, :only => [:show, :index]
  skip_before_filter :edit_auth


  # Find the top users of a particular problem
  def top_users
    @problem = Problem.find(params[:id])
    @solutions = @problem.solutions.where(:status => "correct")
    
    respond_to do |format|
	format.html # top_users.html.erb
        format.json {render json: @problem}

    end
  end

  def mark
    @problems = Problem.all
    @problem = Problem.find(params[:id])
    @solution = Solution.create(:status => "not tried",:path => "")
    @solution.problem = @problem
    @solution.user = current_user

    if @solution.save
      respond_to do |format|
        format.json { render json: @problem , notice: 'Problem was successfully marked. Now you can resolve it!'}
        format.js
      end
    else
      format.json { render error: "error trying to mark" }
      
    end
  end
## Basic Methods ##

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(:code => params[:problem][:code], :name => params[:problem][:name], :description => params[:problem][:description], :input => params[:problem][:input], :output => params[:problem][:output], :test_case_in => " ", :test_case_out => " ")
   
    # Save the uploaded files in public/data
    name_in = "in-" + @problem.code
    name_out = "out-" + @problem.code
    path_in  = save_file(name_in, params[:problem][:file_in])
    path_out = save_file(name_out, params[:problem][:file_out]) 

    @problem.test_case_in = path_in
    @problem.test_case_out = path_out

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.where(:code => params[:problem][:code]).first

    # Save the new files
    name_in = "in-" + @problem.code
    name_out = "out-" + @problem.code 
    path_in=save_file(name_in, params[:problem][:file_in])
    path_out=save_file(name_out, params[:problem][:file_out])

    @problem.test_case_in  = path_in
    @problem.test_case_out = path_out


    respond_to do |format|
      if @problem.update_attributes(:code => params[:problem][:code], :name => params[:problem][:name], :description => params[:problem][:description], :input => params[:problem][:input], :output => params[:problem][:output])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    solutions = @problem.solutions
    solutions.each do |solution|
      solution.destroy
    end
    
    # Delete test case files
    delete_file(@problem.test_case_in)
    delete_file(@problem.test_case_out)   
   
    @problem.destroy
    

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
	  format.js
    end
  end

  
  def is_marked(problem)
    res = false
    if problem.solutions.size > 0
      problem.solutions.each do |solution|
        if solution.user == current_user
          res = true
          break
        end
      end
    end
    return res
  end

  def countsol(problem)
    res = 0
    if problem.solutions.size > 0
      problem.solutions.each do |solution|
        if solution.status != 'not tried'
          res = res + 1
        end
      end
    end
    return res
  end

  def problem_solved(problem)
    res = false

    if problem.solutions.size > 0
       problem.solutions.each do |solution|
          if solution.user == current_user && solution.status == "correct"
	     res = true
             break
          end
       end
    end
    
    return res
  end
  
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/.#index.html.erb
citricn@Louie.3197:1340862037

app/views/problems/.#show.html.erb
citricn@Louie.2316:1340902507

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :input %><br />
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br />
    <%= f.text_area :output %>
  </div>
  <div class="field">
    <%= f.label "Test Case Input" %>
    <%= f.file_field :file_in %>
  </div>
  <div>
    <%= f.label "Test Case Ouput" %>
    <%= f.file_field :file_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/_problem.html.erb
<tr id="<%=problem.id  %>">
    <td align="center"><%= problem.code %></td>
    <td align="center"><%= problem.name %></td>
    <td align="center"><%= controller.countsol(problem) %></td>    
    <td align="center">
    <% if current_user != nil%>
       <% if controller.is_marked(problem) %>
         <% if controller.problem_solved(problem)%>
            Solved |
         <% else %>
            Give it a try |
         <% end %>
      <% else %>
         <%= link_to 'Mark', mark_problem_path(problem), :remote => true%> |
     <% end %>
    <% end %>
    <%= link_to 'Show', problem %>
    <% if current_user != nil and current_user.user_group == 'administrator' %>
    | <%= link_to 'Edit', edit_problem_path(problem) %>
    | <%= link_to 'Destroy', problem ,method: :delete, :remote => true ,data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</tr>

app/views/problems/destroy.js.erb
$('#<%= @problem.id %>').remove();

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<br >
<h1>Listing problems</h1>

<br ><br >
<div id="problems">
<table id="table">
<% if current_user != nil and current_user.user_group == "administrator" %>
   <%= link_to 'New Problem', new_problem_path %>
   <br /><br />
<% end %>

<% if @problems.size > 0  %>
    <% @problems.each do |problem|%>
    
    <% problem.solutions do |solution| %>
    <p> Sirvo</p>
    <%= solution.user %>
    <%= current_user %>
    
    <% end %>
    <% end %>

<table border="1"> 
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Submissions</th>
    <th>Options</th>
  </tr>

<tbody id="body_problems">
<%= render @problems %>
</tbody>

</table>
<% else %>
<p> There are no problems to list.</p>
<% end %>
</table>
</div>
<br />

app/views/problems/mark.js.erb
alert("Problem marked");
$('#body_problems').html("<%= escape_javascript(render @problems) %>");

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<br >

<h1>Problem Detail</h1>
<br >

<% if current_user != nil%>

<% if current_user.user_group == "administrator" %>
   <%= link_to 'Edit', edit_problem_path(@problem) %> |
<% end%>
<%= link_to 'Submissions', problem_solutions_path(@problem) %> |
<%= link_to 'Top Users', top_users_problem_path(@problem) %>
<% end %>
<br ><br >

<p>
  <b>Name:</b>
  <%= @problem.name %>
</p>

<p>
  <b>Code:</b>
  <%= @problem.code %>
</p>

<p>
  <b>Description:</b>
  <%= @problem.description %>
</p>

<p>
  <b>Input:</b>
  <%= @problem.input %>
</p>

<p>
  <b>Output:</b>
  <%= @problem.output %>
</p>



<%= link_to 'Back', request.referer %>

app/views/problems/top_users.html.erb
<br >
<h1>Listing Top Users </h1>

<br ><br >
<% if @solutions.size < 1 %>
   <p>Without submissions there can not be top users. Be the first one!</p>
<% else %>

<table border="1">
  <tr>
    <th>Username</th>
    <th>Status</th>
    <th>Total Submissions</th>
  </tr>

<% @solutions.each do |solution| %>
  <tr>
    <td align="center" ><%= solution.user.username %></td>
    <td align="center"><%= solution.status %></td>
    <td align="center"><%= controller.countsol(solution.user) %></td>
  </tr>
<% end %>
</table>

<br >
<% end %>
<%= link_to 'Back', request.referer  %>
<br />