config/routes.rb
Joal::Application.routes.draw do

  resources :problems do
    member do
      get :mark
    end
  end 
  
  resources :problems do
    resources :solutions
  end
 
  resources :problems do
     member do 
        get :top_users
     end
  end

  
  get "home/index"
  match '' => 'home#index', :as => :home

  resources :users
  resources :users, :user_sessions
  resources :users do
	resources :solutions
  end
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

   root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base


  acts_as_authentic
  attr_accessible :password, :password_confirmation,:crypted_password, :email, :password_salt, :persistence_token, :type, :username,:user_group, :solutions,:problems
  has_many:solutions
  has_many:problems, :through => :solutions

  validates :user_group, :inclusion => { :in => ["administrator", "competitor"]}
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 #before_filter :authenticate, :only => [:index, :edit, :show, :update, :destroy]
 #before_filter :check_auth, :only => [:edit, :update, :destroy]
 skip_before_filter :require_login, :only => [:new, :create]
 skip_before_filter :authorization, :only => [:new, :create, :index, :show, :edit, :update]
 before_filter :edit_auth, :only => [:edit, :update, :destroy]

  def edit_auth
    unless current_user.username == User.find(params[:id]).username
      flash[:notice] = "You may not edit this object"
      if request.referer != nil
        redirect_to request.referer 
      else
        redirect_to :root
      end
        
    end    
  end

## Basic Methods ##

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.user_group = "competitor"

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  
  def countsol(user)
    res = 0
    if user.solutions.size > 0
      user.solutions.each do |solution|
        if solution.status != 'not tried'
          res = res + 1
        end
      end
    end
    return res
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/.#edit.html.erb
citricn@Louie.2316:1340902507

app/views/users/.#index.html.erb
citricn@Louie.3197:1340862037

app/views/users/_form.html.erb
	  <%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
		  <div id="error_explanation">



		    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
		    
		    <ul>
		      <% @user.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		      
		  </div>

	    <% end %>
	    </ul>

	  <% end %>
  
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
	      <div style="clear: both;">&nbsp;</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', request.referer  %>

app/views/users/index.html.erb
<br >
<h1>Listing users</h1>
</br>
<br >
<br >
<% if current_user != nil and current_user.user_group == "administrator" %>
<%= link_to 'New User', new_user_path %>
</br>
</br>
<% end %>

<table border="1">
  <tr>
    <th>Username</th>
    <th>Type</th>
    <th>Sumissions</th>
    <th>Options</th>
  </tr>
  
  <% @users.each do |user| %>
  <tr>
    <td align="center"><%= user.username %></td>
    <td align="center"><%= user.user_group %></td>
    <td align="center"><%= controller.countsol(user) %></td>
    <td align="center"><%= link_to 'Show', user %> 
      <% if current_user.user_group == 'administrator' %>
      | <%= link_to 'Edit', edit_user_path(user) %>
      | <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
  
  <% end %>
</table>



<div style="clear: both;">&nbsp;</div>

app/views/users/new.html.erb
	  <h1>New user</h1>
	  
	  <%= render 'form' %>
	  
	  <%= link_to 'Back', :controller=> 'home', :action => 'index' %>
	  <div style="clear: both;">&nbsp;</div>

app/views/users/show.html.erb
<br >
<h1>Profile - <%= @user.username %></h1>

<br >
<% if current_user == @user %>
   <%= link_to 'Edit', edit_user_path(@user) %>
   | <%= link_to 'Submissions', user_solutions_path(@user)%>
<% elsif current_user.user_group == "administrator" %>
   <%= link_to 'Submissions', user_solutions_path(@user)%>
<% end %>



<br /><br >

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
	  
<p>
  <b>Type:</b>
  <%= @user.user_group %>
</p>


<br />

<%= link_to 'Back', request.referer %>