config/routes.rb
Joal::Application.routes.draw do

  resources :problems do
    member do
      get :mark
    end
  end 
  
  resources :problems do
    resources :solutions
  end
 
  resources :problems do
     member do 
        get :top_users
     end
  end

  
  get "home/index"
  match '' => 'home#index', :as => :home

  resources :users
  resources :users, :user_sessions
  resources :users do
	resources :solutions
  end
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

   root :to => 'home#index'

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  attr_accessible :status,:path 
  belongs_to:user
  attr_accessible :status,:path,:user,:problem
  validates :status, :presence => true 
  belongs_to:user,:autosave => true
  belongs_to:problem

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  skip_before_filter :authorization 
  skip_before_filter :edit_auth

  include ApplicationHelper 

  # GET /solutions
  # GET /solutions.json
  def index
    if params[:problem_id]
	@problem      = Problem.find(params[:problem_id])
	@solutions    = @problem.solutions

        respond_to do |format|
           format.html # index.html.erb
           format.json {render json: @solutions, json: @problem}
        end
    elsif params[:user_id]
        @user       = User.find(params[:user_id])
        @solutions  = @user.solutions
 
        respond_to do |format|
           format.html # index.html.erb
           format.json { render json: @solutions,json:@user }
        end
    end
  end 

  # GET /solutions/1
  # GET /solutions/1.json
  def show
    @solution  = Solution.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @solution}
    end
  end

  # GET /solutions/new
  # GET /solutions/new.json
  def new
    @problem  = Problem.find(params[:problem_id])
    @solution = @problem.solutions.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @solution }
    end
  end

  # GET /solutions/1/edit
  def edit
    @solution = Solution.find(params[:id])
  end

  # POST /solutions
  # POST /solutions.json
  def create
      @problem_user  = Problem.find(params[:problem_id])
      @solution = @problem_user.solutions.create(:status => params[:solution][:status],:path => "")
	@solution.user = current_user
	#####CODIGO PARA VERIFICAR SI LA SOLUCION ES CORRECTA######
	###ARCHIVOS DE PRUEBA###

	
	directory    = "public/solutions"
	id           = @solution.user.username
	path_to_save = files_save(id,params,directory)
	@solution.path=path_to_save
	test_case_in_path      = @problem_user.test_case_in
	test_case_out_path     = @problem_user.test_case_out
	status       = run_solution(path_to_save,test_case_in_path,test_case_out_path,"ruby")
	@solution.status = status

	##########################################################
    respond_to do |format|
      if @solution.save
        format.html { redirect_to problem_solutions_path, notice: 'Solution was successfully created.' }
        format.json { render json: @solution, status: :created, location: @solution }
      else
        format.html { render action: "new" }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /solutions/1
  # PUT /solutions/1.json
  def update
    @solution = Solution.find(params[:id])

    respond_to do |format|
      if @solution.update_attributes(params[:solution])
        format.html { redirect_to problem_solutions_path, notice: 'Solution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @solution = Solution.find(params[:id])
    delete_file(@solution.path)
    @solution.destroy

    respond_to do |format|
      format.html { redirect_to problem_solutions_path }
      format.json { head :no_content }
	  format.js
    end
  end

  def is_marked(problem)
    res = false
    if problem.solutions.size > 0
      problem.solutions.each do |solution|
        if solution.user == current_user
          res = true
          break
        end
      end
    end
    return res
  end

   def countsol(user)
    res = 0
    if user.solutions.size > 0
      user.solutions.each do |solution|
        if solution.status != 'not tried'
          res = res + 1
        end
      end
    end
    return res
  end


  end

app/helpers/solutions_helper.rb
module SolutionsHelper



end

app/views/solutions/.#index.html.erb
citricn@Louie.2316:1340902507

app/views/solutions/_form.html.erb
<%= form_for([@solution.problem,@solution]) do |f| %>
  <% if @solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solution.errors.count, "error") %> prohibited this solution from being saved:</h2>

      <ul>
      <% f.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Solution file" %>
    <%= f.file_field :path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solutions/destroy.js.erb
$('#<%= @solution.id %>').remove();

app/views/solutions/edit.html.erb
<h1>Editing solution</h1>

<%= render 'form' %>

<%= link_to 'Show', problem_solution_path(@solution.problem,@solution) %>
<%= link_to 'Back', problem_solutions_path(@solution.problem) %>

app/views/solutions/index.html.erb
<br >
<h1>Listing solutions</h1>


<br ><br >
<% if @problem %>
    <% if controller.is_marked(@problem) == true %>
     <%= link_to 'New Solution', new_problem_solution_path %>
     <br /><br />
    <% end %>

<% end %>

<% if @solutions.size > 0 %>

<% if @user && (current_user != @user || current_user.user_group != "administrator") %>
   <p>You may not see other competitors submissions</p>
<% else %>

<table id="table", border=1>
  <tr>
    <th>Code</th>
    <th>Status</th>
    <th>Problem</th>
<% if @problem %>
    <th>User</th>
<% end %>
    <th>Options</th>
  </tr>

<% @solutions.each do |solution| %>
  <% if @problem  %>

  <% if  solution.status.to_s != "not tried" %>
    <tr id="<%=solution.id  %>">
      <td align="center"><%= solution.id %></td>
      <td align="center"><%= solution.status %></td>
      <td align="center"><%= solution.problem.name %></td>
      <td align="center"><%= solution.user.username %></td>
      <td align="center"><%= link_to 'Show', problem_solution_path(@problem,solution) %>
      <% if current_user != nil and current_user.user_group == 'administrator' %>
      | <%= link_to 'Destroy', problem_solution_path(@problem,solution) , method: :delete, :remote => true, :confirm => 'Are you sure?' %></td>
    <% end %>

  <% end %>
    </tr>
  <% elsif @user && current_user == solution.user %>
     <tr>
       <td align="center"><%= solution.id %></td>
       <td align="center"><%= solution.status %></td>
       <td align="center"><%= solution.problem.name %></td>
       <td align="center"><%= link_to 'Show', user_solution_path(@user,solution) %>
       <% if current_user != nil and current_user.user_group == 'administrator' %>
       | <%= link_to 'Destroy', user_solution_path(@user,solution), method: :delete,:remote => true, data: {confirm: 'Are you sure?'}%></td>
       <% end %>
     </tr>

  <% end %>

<% end %>
</table>

<%end%>

<% elsif @problem %>
   <p>There are no solutions to list. Please submit one!</p>
<% elsif @user %>
   <% if @user == current_user %>
      <p>You have not submitted any solutions.</p>
   <% else %>
      <p>No solutions to list for now.</p>
   <% end %>
<% end %>

<br />

<div id="test">
</div>

<%= link_to 'Back', request.referer  %>

app/views/solutions/new.html.erb
<h1>New solution</h1>


<%= render 'form' %>



<%= link_to 'Back', problem_solutions_path %>

app/views/solutions/show.html.erb
<h1> Solution Detail </h1>

<br >

<p>

  <b>Status:</b>
  <%= @solution.status %>
</p>

<p>
  <b>Owner:</b>
  <%= @solution.user.username unless @solution.user.nil? %>
</p>

<p>
  <b>Problem:</b>
  <%= @solution.problem.name %>
</p>

<p>
  <b>Date:</b>
  <%= @solution.created_at %>
</p>
<pre class="brush: ruby">
<%= dump_file(@solution.path)   %>
</pre>
<%= link_to 'Back', problem_solutions_path(@solution.problem) %>