config/routes.rb
Joal::Application.routes.draw do

  resources :problems do
    member do
      get :mark
    end
  end 
  
  resources :problems do
    resources :solutions
  end
 
  resources :problems do
     member do 
        get :top_users
     end
  end

  
  get "home/index"
  match '' => 'home#index', :as => :home

  resources :users
  resources :users, :user_sessions
  resources :users do
	resources :solutions
  end
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

   root :to => 'home#index'

end

app/views/layouts/.#application.html.erb
citricn@Louie.2478:1341033367

app/views/layouts/.#sidebar.html.erb
citricn@Louie.2478:1341033367

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!-- FONT HERMOSO REVISAR SI NECESITA INTERNET-->
<link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>

<script type="text/javascript">
     SyntaxHighlighter.all()
</script>
</head>

<body>


  
  <div id="wrapper">
    <div id="header-wrapper">
      <div id="header">
	<div id="logo">
	  <h1>Joal</h1>
             <p>virtual judge</p>	      
	</div>
      </div>
    </div>

    <div id="menu-wrapper">
      <div id="menu">
	<ul>
	  <li><%= link_to "Home", :home %> </li>
	  <li><%= link_to "Users", users_path %> </li>
	  <li><%= link_to "Problems", problems_path %></li>
          
	</ul>
      </div>
    </div>
    

    <div id="page">
      <!-- MARGENES DE LA PAGINA -->
      <div id="page-bgtop">
	<div id="page-bgbtm"> 
	 <div id="page-content">
	     <div id="sidebar">
	       <ul>
		 <% if current_user %>
		 <li> <h2> <%= current_user.username %> </h2></li>
		 <ul>
		   <li> <a> <%= link_to "Profile", current_user%></a></li>
		   <li> <a> <%= link_to "Logout", :logout%></a></li>
		 </ul>
		 <% else %>
		 <li><h2> <%= link_to "Register", new_user_path%> </h2></li>
		 <li><h2> <%= link_to "Login", :login %></h2></li>
		 <% end %>
	       </ul>	      
	     </div>  
	   <div id="content">
	     <% if flash[:notice] %>
	     <div style="clear: both;">&nbsp;</div>   
	     <div id="notice"><%= flash[:notice] %></div>


	     <% end %>
	     
	     <%= yield %>   
      	     
	     <div style="clear: both;">&nbsp;</div>
	     

	     

           <div style="clear: both;">&nbsp;</div>
	   </div> 
	 </div>  
	</div>
      </div>
    </div>
    
    
  </div>
  
  <div id="footer">
    <p>Joal - Virtual Judge/ci-5644 </p>
  </div>
  <!-- end #footer -->
  
</body>

</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
<head>

<!-- FONT HERMOSO REVISAR SI NECESITA INTERNET-->
<link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>

<div id="sidebar">
  <ul>
    <% if current_user %>
    <li> <h2> <%= current_user.username %> </h2></li>
    <ul>
      <li> <a> <%= link_to "Profile", current_user%></a></li>
      <li> <a> <%= link_to "Logout", :logout%></a></li>
    </ul>
    <% else %>
    <li><h2> <%= link_to "Register", new_user_path%> </h2></li>
    <li><h2> <%= link_to "Login", :login %></h2></li>
    <% end %>
  </ul>	      
</div>  

</body>

</html>